#
# Jekyll configuration
#

# User data
title: Personal website
description: > 


# Collections
collections:
  posts:
    output: true
    permalink: :collection/:title
  projects:
    output: true
    permalink: :collection/:title
  pages:
    output: true
    parmalink: :collection/:title

# Defaults
defaults:
  -
    scope:
      path: ""
      types: pages
    values:
      layout: "minimalistic/layout_page"
  -
    scope:
      path: ""
      type: projects
    values:
      layout: "minimalistic/layout_post"
      category: Projects
      author: Ángel Guerrero
  -
    scope:
      path: ""
      type: posts
    values:
      layout: "minimalistic/layout_post"
      category: Posts
      image: "abstract-code.jpg"
      published: false
      author: Ángel Guerrero

# Plugins
# whitelist:
# plugins:
  # - jemoji

# Serving
detach:  false
port:    4000
host:    127.0.0.1
url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/angel" # the subpath of your site, e.g. /blog
show_dir_listing: false

liquid:
  error_mode: warn

# Conversion
markdown:    kramdown

# sass
sass:
  style: compressed

# Markdown Processors
kramdown:
  auto_ids:       true
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  input:          GFM
  hard_wrap:      false
  footnote_nr:    1
  
  syntax_highlighter_opts:
    table_class: 'rouge-table'
    # css_class: 'hljs'
    block:
      line_numbers: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
