#
# Jekyll configuration
#

# User data
title: ﾃ］gel Guerrero Blog
description: > 

# Serving
detach:  false
port:    4000
host:    127.0.0.1
url: "https://angelguerrero.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/angel" # the subpath of your site, e.g. /blog
show_dir_listing: false

# Variables
img_dir: /assets/img

# Collections
collections:
  posts:
    output: true
    permalink: :collection/:title
  projects:
    output: true
    permalink: :collection/:title
  pages:
    output: true
    parmalink: :collection/:title
  exercises:
    output: true
    permalink: :collection/:title

# Defaults
defaults:
  -
    scope:
      path: "_pages/"
      types: pages
    values:
      layout: "minimalistic/layout_page"
  -
    scope:
      path: "_posts/"
      type: posts
    values:
      image: "assets/img/defaults/abstract-code.jpg"
      author: "ﾃ］gel Guerrero"
  -
    scope:
      path: "_projects/"
      type: projects
    values:
      image: "assets/img/defaults/abstract-code.jpg"
      author: "ﾃ］gel Guerrero"
  -
    scope:
      path: "_exercises/"
      type: exercises
    values:
      image: "assets/img/defaults/abstract-code.jpg"
      author: "ﾃ］gel Guerrero"

# Iterable collections where you want
iterable_collections: ["posts", "projects", "exercises"]

# Plugins
plugins:
  - jemoji
  - jekyll-menus

liquid:
  error_mode: warn

# sass
sass:
  style: compressed

# Conversion
markdown: kramdown
highlighter: rouge

# Markdown Processors
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - package.lock.json
  - package.json
  - webpack.config.js
  - src
  - .editorconfig
  - .eslintignore
  - .eslintrc.js